### ISSUE TITLE
how to configure kuwo in config.json?

### ISSUE THREAD

**Issue by huidaoweilai2024** [lxmusics/lx-music-api-server-python#33]
how to configure kuwo in config.json?

**Comment by helloplhm-qwq** [comment]
google.com plz

i dont provide the available-vip bypass configuration because i dont want the repo was down for some reason

the default configure needs vip account(for all the music platforms)

or u can have a see in the pull requests page

i remembered that someone opened a pr with vip-bypass code

but i didnt merge that

(only kuwo)

you can configure your own project according to that pr

**Comment by helloplhm-qwq** [comment]
have a see in #20 

if u want to know the meaning of each configuration items, plz see the comment in the config.json file, i think i have written it clearly

if u have a des configure, like this pr, u can change the `proto` item to kuwodes, and configure it with the API request method that u know
